return {
    { 'jinh0/eyeliner.nvim',
        event = 'VeryLazy',
        opts = {
            highlight_on_key = true,
        },
    },
    { 'ThePrimeagen/harpoon',
        dependencies = { 'nvim-lua/plenary.nvim' },
        event = 'VeryLazy',
        keys = {
            { '<leader>hn', function () require('harpoon.mark').add_file() end, desc = '[h]arpoon [n]ew Mark' },
            { '<leader>hb', function () require('harpoon.ui').toggle_quick_menu() end, desc = '[h]arpoon [b]ufffer Menu' },
            { '<leader>hh', function () require('harpoon.ui').nav_file(1) end, desc = '[h]arpoon First File' },
            { '<leader>hj', function () require('harpoon.ui').nav_file(2) end, desc = '[h]arpoon Second File' },
            { '<leader>hk', function () require('harpoon.ui').nav_file(3) end, desc = '[h]arpoon Third File' },
            { '<leader>hl', function () require('harpoon.ui').nav_file(4) end, desc = '[h]arpoon Fourth File' },
            { '<leader>h;', function () require('harpoon.ui').nav_file(5) end, desc = '[h]arpoon Fifth File' },
        },
    },
    { 'chentoast/marks.nvim',
        event = 'VeryLazy',
        config = true,
    },
}
